### ISSUE TITLE
repack.sh on debian

### ISSUE THREAD

**Issue by masc-git** [linux-surface/surface-uefi-firmware#1]
hi!

on debian i need to use the bash, otherwise some of the commands don't work. 

--- repack_orig.sh	2020-04-02 16:27:17.000000000 +0200
+++ repack.sh	2020-04-20 10:08:40.093902643 +0200
@@ -1,4 +1,4 @@
-#!/bin/sh
+#!/bin/bash
 
 DIR=$(readlink -f $(dirname $0))

thanx.

**Comment by StollD** [comment]
Thanks! I've made some changes, now it should run without issues under debian.

**Comment by sphh** [comment]
I just want to confirm, that the `.repack.sh` skript is running fine on the Debian based  Ubuntu based Linux Mint 20.1.
