### ISSUE TITLE
Surface 3 

### ISSUE THREAD

**Issue by joni909** [linux-surface/surface-uefi-firmware#4]
I'm following this but when I come to repack stage it always ends with this:

 ./repack.sh -m cab -f ../Surface3_WiFi_Win10_18362_1902003_0.msi -o out
 ==> Found Model: Surface3
 ==> Unpacking driver package
./repack.sh: line 133: cd: out/Surface3/*: No such file or directory
basename: missing operand
Try 'basename --help' for more information.
basename: missing operand
Try 'basename --help' for more information.
basename: missing operand
Try 'basename --help' for more information.
cp: missing destination file operand after '/tmp/tmp.G3DcbF3vlA/firmware.bin'
Try 'cp --help' for more information.
cp: missing destination file operand after '/tmp/tmp.G3DcbF3vlA/firmware.cat'
Try 'cp --help' for more information.
cp: missing destination file operand after '/tmp/tmp.G3DcbF3vlA/firmware.inf'
Try 'cp --help' for more information.
sed: can't read /tmp/tmp.G3DcbF3vlA/firmware.inf: No such file or directory

can someone help me see what's wrong here

I opened a reddit thread too
https://www.reddit.com/r/SurfaceLinux/comments/h0z0fs/surface_3_firmware/?utm_medium=android_app&utm_source=share

**Comment by anhphanhai** [comment]
I have the same issue with Surface Pro 7. Please help

**Comment by wmjb** [comment]
have same issue with surface pro 3 with all msi firmware release using ubuntu-20.04.3-desktop-amd64

**Comment by qzed** [comment]
I believe this happens if you're missing the `msiextract` tool. I've prepared #15 to improve feedback in case of errors.

**Comment by kepi** [comment]
I suppose this can be closed?

**Comment by joni909** [comment]
Yeah, I just tried this and it worked smooth to install the cab files now.
I basically forgot about this for a while but I'm closing it now
