### ISSUE TITLE
fwupd < 1.4.0 complains about hex version numbers

### ISSUE THREAD

**Issue by yesrod** [linux-surface/surface-uefi-firmware#6]
In commit afdaf5a68be332c4cce55448e8c4bd3f9ec34560 processing of the hex version number to triplets was removed.  However, distros as recent as Ubuntu 20.04 are still shipping versions of fwupd lower than 1.4.0, so it would be nice if that processing still happened.

(I just re-implemented the same thing less elegantly and went to submit a PR before I noticed that the exact same thing had already been removed.)

**Comment by StollD** [comment]
Ah well. I thought that would get at least backported to the debian based distros.

I'll revert the commit. Thanks for the heads up.

**Comment by yesrod** [comment]
Thanks, that worked for me, I was able to install an ME firmware update on my Surface Go after that change.
