### ISSUE TITLE
Surface Go September firmware update - firmware is older than installed 89.91.17692 < 1494442258?

### ISSUE THREAD

**Issue by mannp** [linux-surface/surface-uefi-firmware#9]
Hi there I am trying to update my Surface Go to the latest Sept firmware with fwupdmgr 1.4.6 and I am getting the above error.

I haven't updated the firmware since removing windows and installing arch linux, so I do not believe I have this firmware installed.

I wondered how I could go about debugging the issue?

Thanks in advance

Firmware -> https://support.microsoft.com/en-us/help/4455978/surface-go-update-history
File -> SurfaceGo-WiFi_Win10_18362_20.085.33990_WiFi_0.msi
Bios -> UEFI 1.0.19

**Comment by StollD** [comment]
Microsoft likes to randomly change the version number that is used by the UEFI to a lower one.

I had that issue too when I recently installed the latest updates, and a few times before that.

If you want you can tell fwupd to allow downgrages (`fwupdmgr --allow-older` or so), then it should flash fine.

**Comment by mannp** [comment]
> Microsoft likes to randomly change the version number that is used by the UEFI to a lower one.

I see okay, thanks for the info.

Did you install all 4 of the cab files available for your device, as with the version numbers I am unclear which ones needs updating.

**Comment by StollD** [comment]
Just flash all of them. fwupd will show the same error if the version number is actually the same. Once you flash them with `--allow-older` it will tell you that the version is already installed.

**Comment by mannp** [comment]
Just done exactly that and 2 gave wrong version of flash utility error and only the UEFI flashed.

I have now gone from UEFI 1.0.19 to UEFI 1.0.28 but not the latest 1.1.18.0 from September 2020, so maybe just a matter of the downloads not being available yet?

btw thanks for creating this, its great :+1:

**Comment by ShapeShifter499** [comment]
If I get the cab files from the repack script it works fine for me with this command 
```fwupdmgr install --allow-older out/SurfaceGo-WiFi/SurfaceGo-WiFi_ISH_3.1.0.3524.cab```

I'm currently on Arch Linux

**Comment by mannp** [comment]
Thanks @ShapeShifter499 for the further confirmation :) it worked for me with the --allow-older option and I should have closed this.
